name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Deploy
        run: |
          rmarkdown::render_site()
        shell: Rscript {0}
